### ISSUE TITLE
License on the project will be good

### ISSUE THREAD

**Issue by Pacific01** [dandoh/web-haskell-graphql-postgres-boilerplate#2]
Hello.

First of all I wat to thank you (@dandoh) for this boilerplate. It helps me, a lot, to understand how to make a setup for a Haskell web application. I have use it in on of my side project as my base, which led me to think about whether I can use it or not license wise.

It will be great if it can has some license.

I have seen a lot of BSD-3-Clause and MIT aswell in the haskell comunity and both of them will be okay.

Thank you.

**Comment by dandoh** [comment]
Hi @Pacific01 
I added MIT Licence.
Feel free to tell me if you have any issue.

Stay safe!

**Comment by Pacific01** [comment]
Nice. 😁

In fact I have a little pull request prepared in it I have added some Docker{file, composer,...} so anyone can easily run and test it.

Thank you!

**Comment by dandoh** [comment]
@Pacific01 That would be superb! Please send your PR 🙇
