### ISSUE TITLE
error: JSON.parse

### ISSUE THREAD

**Issue by locallycompact** [dandoh/web-haskell-graphql-postgres-boilerplate#7]
Hi, I think I set this up correctly and I'm using the query

```
query {
  myUserInfo {
    name
  }
}
```

but I just get this error with no much information

```
{
  "error": "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
}
```

I admit I don't know graphql that well but what can I do to get a more useful error?

**Comment by dandoh** [comment]
@locallycompact Can you provide additional information, e.g, step to reproduce the bug, which operating system?

**Comment by bradsherman** [comment]
I am getting the same error on wsl 2 (Ubuntu 18.04) when I run the `myUserInfo` query or the `changePassword` mutation. `login` and `register` work fine so maybe it has something to do with the JWT? I do have the token included in the http headers in the GraphQL playground as well.

Side note: thanks for making this! I just started learning Haskell and I've learned a ton already from setting this up and trying to create my own app.

**Comment by dandoh** [comment]
@bradsherman Could you checkout the branch `debug`, run the query and see what's logged?

Basically I added printing:
![image](https://user-images.githubusercontent.com/10379980/86134534-f193f600-bb13-11ea-927f-47403937a378.png)

**Comment by bradsherman** [comment]
I just see it say "Error" and then "Unauthorized". I can see that the "currentUserId" is Nothing so it must be something with parsing the jwt

**Comment by bradsherman** [comment]
I think I found the problem. My Authorization header was "Bearer <token>" as I have grown used to doing it that way. It works if I remove "Bearer "

**Comment by dandoh** [comment]
@bradsherman Thank you for supporting.

I've pushed a fix to master that accept authorization header with/without bearer, as well as returning the error response properly followed the Graphql spec (https://github.com/dandoh/web-haskell-graphql-postgres-boilerplate/commit/6f24d43dabdc4262cf1c60986062337cba0a696c)

I'll close this issue as this would solve the problem. If it persists feel free to reopen the issue.
