### ISSUE TITLE
Array Objects

### ISSUE THREAD

**Issue by bradsherman** [dandoh/web-haskell-graphql-postgres-boilerplate#9]
Hello,

I noticed that in the most recent commit, things like `MaybeObject` and `ArrayObject` were removed in favor of `Composed`. I was originally trying to return an array of `User`s with `ArrayObject` and have since updated to `Composed`, but either way I have not been able to get it compiling. Would it be possible to include an example that implements the following query?

```
type Query {
  ...
  allUsers: [User!]!
  ...
}
```

I tried looking at the morpheus documentation as well, but it looks quite different from the patterns used here. I'm new so I'm sure I'm missing something but any help would be appreciated!

**Comment by Pacific01** [comment]
Hello everyone

You are right @bradsherman I have had the same problem, luckily I have found some solutions and examples. Not easy tho.

I'm gonna make a pull request  #10 adding a `allUsers` endpoint to the API, as an example, but I'm gonna try to explain it on here too. I'm no expert on haskell neither morpheus so Maybe "not the best implementation"

<details><summary>Detailed implementation:</summary><p>

- Add the new endpoint to the `schema.graphql` file. Exactly as you have done:
```graphql
type Query {
  ...
  allUsers: [User!]!
  ...
}
```

- Add the new query and queryResolver to the list
```hs
queryResolver = Query 
  { ...
  , allUsers = allUsersResolver
  ...
}
```

- Add the implementation of the queryResolver: Notice that it uses `runSelect` combined with `userSelect` to get the `[DB.User]` and then you traverse (`traverse :: (Traversable t, Applicative f) => (a -> f b) -> t a -> f (t b)`) it with `userResolver` those three functions (runSelect, userSelect and userResolver) exists in the code base or the Prelude.
```hs
-------------------------------------------------------------------------------
allUsersResolver :: GraphQL o => Composed o [] User
allUsersResolver = do
  res :: [DB.User] <- runSelect userSelect
  traverse userResolver res
```

- And that's it*: If you try it with the graphiql you will have a list of users as a result.
(http://localhost:8080/graphiql)
```graphql
query {
  allUsers {
    name,
  }
}
```

*Except maybe that's not it. It's posible that stack, cabal or docker has not notices the changes to the `schema.graphql` and therefore has not added the new endpoint, types and everything is failing. In that case try to relaunch the building process and start from scratch. I have stopped the dockers and I have eliminated them with docker stop and docker rm, but i have done other things to, I'm not sure witch of that things have worked. And some of that things are very slow.
</p></details>

This are the documentation, solutions and examples I have found:
- [An example of code with morpheus-graphql where implements some solutions with Composed](https://github.com/morpheusgraphql/morpheus-graphql/blob/master/morpheus-graphql-examples-scotty/src/Server/MonadIO/API.hs)

- [Same example with the scheme.graphql part](https://github.com/morpheusgraphql/morpheus-graphql/blob/master/morpheus-graphql-examples-scotty/src/Server/MonadIO/schema.graphql)

Hope it will help you.

**Comment by bradsherman** [comment]
thank you for the detailed explanation @Pacific01! Those examples are exactly what I needed. I was unaware of the `traverse` function, works like a charm after using that.

**Comment by Pacific01** [comment]
I completely blow my mind when I saw it. Even if I learn about it a couple of days ago I would never have thought of using it. It is difficult to see when a type applies or not. In this case my first try was with `fmap` something like `fmap userResolver users` but it didn't work.

I'm glad you like it and it works.

**Comment by dandoh** [comment]
Yes, because `userResolver` is still within Monad/Applicative so we'll need `traverse` or `mapM`.

Thanks @Pacific01. PR merged.
Feel free to close the issue if this nolonger troubles you @bradsherman

**Comment by bradsherman** [comment]
closing the issue, thanks all for the help.
